### ISSUE TITLE
Error in composer require your bundle

### ISSUE THREAD

**Issue by Visioweb** [leandro980/skebby-bundle#1]
Hello,
I tried to install this bundle with composer on symfony 5, but typing
composer require leandro980 / skebby-bundle after a while the error comes out:

 In ArrayNode.php line 216:
!!                                                                           
!!    The child node "username" at path "szopen_skebby" must be configured.

would it be possible to fix this problem?
Many thanks in advance.

**Comment by LeandroLuccerini** [comment]
> Hello,
> I tried to install this bundle with composer on symfony 5, but typing
> composer require leandro980 / skebby-bundle after a while the error comes out:
> 
> In ArrayNode.php line 216:
> !!
> !! The child node "username" at path "szopen_skebby" must be configured.
> 
> would it be possible to fix this problem?
> Many thanks in advance.

Hello, let me take a look and i'll fix it as soon as possible. Thanks.

**Comment by LeandroLuccerini** [comment]
In the meanwhile complete the configuration step before the installation, then re-run the composer command

In your ```config/packages/skebby_bundle.yaml```:
```yaml
skebby:

  # Add your Skebby account credentials
  username: 'yourskebbyusername'
  password: 'yourskebbypassword'
  
  # Skebby provides two kinds of authentication:
  #   - Getting a Session Id that expires in 5 minutes if no request is sent
  #   - Getting a Token always valid
  # Allowed values are: 
  #   - token (default)
  #   - session
  #
  # auth_type: 'token'
  
  # You can choose which kind of sms send between:
  #   - "GP" for Classic+ (limited to 1530 chars, delivery warranty, delivery report)
  #   - "TI" for Classic (limited to 1530 chars, delivery warranty)
  #   - "SI" for Basic (limited to 160 chars, no delivery warranty)
  #
  # message_type: 'TI'
  
  # You can also add a default sender alias used to send SMS.
  # This overrides the default alias set in Skebby account but must be one of the alias 
  # already registered. 
  # If the message type allows a custom TPOA and the field is left empty, the user’s preferred TPOA
  # is used. Must be empty if the message type does not allow a custom TPOA.
  #
  # default_sender_alias: ~
```

Then 
```sh
$ composer require leandro980/skebby-bundle
```
